orbs: # declare what orbs we are going to use
  node: circleci/node@4.0.0 # the node orb provides common node-related configuration 
  browser-tools: circleci/browser-tools@1.1.1

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build-api:
    executor: node/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - checkout  
      - run: cd ./api && npm install
      - run: cd ./api && npm run build

  build-app:
    executor: node/default
    working_directory: ~/project
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: .
      - checkout  
      - run: cd ./component && npm install
      - run: cd ./component && npm run build

  build-test:
    executor: node/default
    working_directory: ~/project
    steps:
      - browser-tools/install-chrome
      - attach_workspace:
          at: .
      - checkout  
      - run: cd ./component && npm install
      - run: cd ./component && npm run build
      - run: cd ./component && npm run test-headless
      - run: cd ./component && npm run e2e

workflows:
  version: 2
  build:
    jobs:
      - build-api
      - build-app
      - build-test
